language: generic
env:
  - HEAD=yes
  - HEAD=no
sudo: false


addons:
  apt:
    packages:
      - language-pack-ja
      - vim
      - libperl-dev
      - python-dev
      - python3-dev
      - liblua5.1-0-dev
      - lua5.1

install:
  - bash install-vim.sh
  - if [ x"$HEAD" = "xyes" ]; then export PATH=$HOME/vim/bin:$PATH; fi

before_script:
    - git clone https://github.com/syngan/vim-vimlint --branch grep /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 /tmp/vim-themis
  - git clone https://github.com/Shougo/vimproc.vim /tmp/vimproc
  - (cd /tmp/vimproc && make)

script:
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 -c func_abort=1 autoload
  # - /tmp/vim-themis/bin/themis --runtimepath /tmp/vimproc --reporter dot
  - /tmp/vim-themis/bin/themis --runtimepath /tmp/vimproc --exclude ConcurrentProcess --reporter dot
notifications:
  webhooks:
    urls:
      - http://travis-ci.herokuapp.com/vim
    on_success: never
    on_failure: always
    on_start: false
